# Generated by Django 3.1.4 on 2023-01-24 16:23

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDoLocal', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='NomeDoLocal')),
                ('FotoDoAnuncio', models.CharField(max_length=400)),
                ('SobreLocal', models.TextField()),
                ('RedesSociais', models.TextField()),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.cidade')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.topic')),
            ],
        ),
    ]
