# Generated by Django 3.1.4 on 2023-01-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='NomeDoLocal',
            new_name='title',
        ),
    ]
