# Generated by Django 4.0.8 on 2023-02-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_auto_20230126_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='local',
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
