# Generated by Django 4.0.8 on 2023-02-01 14:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia', '0003_remove_local_cidade_remove_local_topic_delete_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(default='', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Nome')),
                ('FotoDoAnuncio', models.CharField(max_length=400)),
                ('SobreLocal', models.TextField()),
                ('RedesSociais', models.TextField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.categoria')),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.cidade')),
            ],
        ),
    ]
