# Generated by Django 4.0.8 on 2023-02-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='local',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='local',
            name='Plano',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
