# Generated by Django 3.1.4 on 2023-02-03 13:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='NomeCidade'),
        ),
    ]
