# Generated by Django 3.2 on 2023-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0010_auto_20230209_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='Foto1',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto10',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto2',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto3',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto4',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto5',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto6',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto7',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto8',
            field=models.CharField(default='non-exist', max_length=400),
        ),
        migrations.AddField(
            model_name='local',
            name='Foto9',
            field=models.CharField(default='non-exist', max_length=400),
        ),
    ]
