# Generated by Django 3.2 on 2023-02-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0011_auto_20230214_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='FaceBook',
            field=models.CharField(default='non-exist', max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='Instagram',
            field=models.CharField(default='non-exist', max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='WhatsApp',
            field=models.CharField(default='non-exist', max_length=200),
        ),
    ]
