# Generated by Django 3.2 on 2023-02-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0012_auto_20230214_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='Site',
            field=models.CharField(default='non-exist', max_length=200),
        ),
    ]
