name: docker-compose-actions-workflow
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy vps
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd home/user/repo-guia-oficial
            docker-compose stop
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d --build
